# [neocmakelsp] https://github.com/neocmakelsp/neocmakelsp

command_upcase = "ignore" # "lowercase", "upcase"
# cmake-lint integration
enable_external_cmake_lint = false # true to use external cmake-lint
# internal lint
line_max_words = 120 # this define the max words in a line
